// <auto-generated />
using System;
using DiscordBot.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiscordBot.DataAccess.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20200920105147_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-preview.8.20407.4");

            modelBuilder.Entity("DiscordBot.DataAccess.Entities.Message", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("CharCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChannelId" }, "Idx_Message_ChannelId");

                    b.HasIndex(new[] { "CreateDate" }, "Idx_Message_CreateDate");

                    b.HasIndex(new[] { "UserId" }, "Idx_Message_UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DiscordBot.DataAccess.Entities.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MessageId" }, "Idx_Poll_MessageId")
                        .IsUnique();

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("DiscordBot.DataAccess.Entities.Pollvote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PollId")
                        .HasColumnType("int");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("VoteOption")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.HasIndex(new[] { "UserId" }, "Idx_Pollvote_UserId");

                    b.ToTable("Pollvotes");
                });

            modelBuilder.Entity("DiscordBot.DataAccess.Entities.Pollvote", b =>
                {
                    b.HasOne("DiscordBot.DataAccess.Entities.Poll", "Poll")
                        .WithMany("Pollvotes")
                        .HasForeignKey("PollId");
                });
#pragma warning restore 612, 618
        }
    }
}
